<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // async 异步； sync同步    await 等待 ；
        // async 和 await 调用 ； 简化了 then的链式调用 。利用同步的写法 实现异步顺序的控制；

        function fn1() {
            return new Promise(resolve => {
                setTimeout(() => {
                    resolve(111)
                }, 1000);
            })
        }

        function fn2() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    // resolve(2222)
                    reject("error2222");
                }, 1000);
            })
        }

        function fn3() {
            return new Promise(resolve => {
                setTimeout(() => {
                    resolve(333)
                }, 1000);
            })
        }



        // promise里的then 来实现 链式调用 ；
        // 异步函数 移除执行  
        // fn1().then(res=>{
        //     console.log(res);
        //     return fn2();
        // }).then(res=>{
        //     console.log(res);
        //     return fn3();
        // }).then(res=>{
        //     console.log(res);
        // }).catch(err=>{
        //     console.log(err);
        // })

        async function fn() {
            try {
                let res1 = await fn1(); // 会等待 后面的promise对象 调用 resolve 或者 reject 方法；
                console.log(res1);
                let res2 = await fn2();
                console.log(res2);
                let res3 = await fn3();
                console.log(res3)
            } catch (err){
                console.log(err);
            }

        }
        fn();

        // fn1().then(res=>{
        //     console.log(res);
        // })
        // fn2().then(res=>{
        //     console.log(res);
        // })
        // fn3().then(res=>{
        //     console.log(res);
        // })



        // try {
        //     console.log(a);
        // } catch (err) {
        //     console.log(err);
        // }



    </script>
</body>

</html>